services:
  - type: web
    name: debt-payoff-planner-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: a51fa59ddf4f3822c5a30de5479fa6a0a0d229b94240bae731ec02f6162c0034
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

databases:
  - name: debt-planner-db
    databaseName: debt_planner
    user: debt_planner_user
    plan: free 